// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace OpenLayoutDemo
{
    public class OpenLayoutDemoOutputs: SystemResults
    {
		/// <summary>
		/// The number of placed instances.
		/// </summary>
		[JsonProperty("Instances")]
		public double Instances {get; set;}



        /// <summary>
        /// Construct a OpenLayoutDemoOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public OpenLayoutDemoOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a OpenLayoutDemoOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public OpenLayoutDemoOutputs(double instances): base()
        {
			this.Instances = instances;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}